import { defineConfig, defineDocs } from "fumadocs-mdx/config";

// Docs live in ./content/docs as MDX. fumadocs-mdx codegens .source/ from them
// (git-ignored; regenerated by the postinstall + the build script's `fumadocs-mdx` step).
export const { docs, meta } = defineDocs({
	dir: "content/docs",
});

export default defineConfig();
