/* Auto-generated by cbindgen — do not edit manually. */
/* Build: cd libs/structured-logs && cbindgen --config cbindgen.toml --crate structured-logs --output structured_logs.h */


#ifndef STRUCTURED_LOGS_H
#define STRUCTURED_LOGS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle for C FFI.
 *
 * Owns a `Terminal` (VTE parser) so the C binary doesn't need to share its
 * own parser state. The C binary's `WriteString` still runs for display;
 * this handle drives a parallel parse purely for structured logging.
 */
typedef struct StructuredLogHandle StructuredLogHandle;

/**
 * Initialize structured logging for a session.
 *
 * Returns an opaque handle, or null on error.
 *
 * # Safety
 *
 * `session_name` and `log_dir` must be valid null-terminated C strings.
 */
struct StructuredLogHandle *structured_log_init(const char *sessionName,
                                                const char *logDir,
                                                uint32_t cols,
                                                uint32_t rows);

/**
 * Feed raw PTY output bytes to the structured logger.
 *
 * Call this after every PTY read in the C binary.
 *
 * # Safety
 *
 * `handle` must be a valid pointer from `structured_log_init`.
 * `data` must point to `len` valid bytes.
 */
void structured_log_process(struct StructuredLogHandle *handle, const uint8_t *data, uintptr_t len);

/**
 * Notify the structured logger of a terminal resize.
 *
 * # Safety
 *
 * `handle` must be a valid pointer from `structured_log_init`.
 */
void structured_log_resize(struct StructuredLogHandle *handle, uint32_t cols, uint32_t rows);

/**
 * Flush all writers and free the handle.
 *
 * # Safety
 *
 * `handle` must be a valid pointer from `structured_log_init`.
 * After this call, the handle is invalid and must not be used.
 */
void structured_log_shutdown(struct StructuredLogHandle *handle);

/**
 * Restore a session from its `.grid.jsonl` file.
 *
 * Reads the grid log, produces ANSI output, and writes it to stdout.
 * Returns 0 on success, -1 on error (caller should fall back to legacy restore).
 *
 * # Safety
 *
 * `log_dir` and `session_name` must be valid null-terminated C strings.
 */
int32_t structured_log_restore(const char *logDir, const char *sessionName);

#endif  /* STRUCTURED_LOGS_H */
